### ISSUE TITLE
docker container start failed

### ISSUE THREAD

**Issue by Arthur-Ling** [kazutoiris/connectal-docker#1]
Hello, I pull your connectal-docker image form docker hub. When I try to docker start a container, the status of it changes from "runing" to "exited" fast, and I try to  "docker exec -it " it, it has "Error response from daemon: container is not running". Is there any wrong with my  shell cmd or my docker installs wrong?

**Comment by kazutoiris** [comment]
Thank you for reaching out regarding the issue you are facing with the connectal-docker image. Based on your description, I would like to address the following points:

1. It is normal for the container to change its status from "running" to "exited" quickly when using a headless build. Headless builds are designed to execute a single task or command and then exit, rather than running continuously like interactive containers.

2. If you want to obtain a persistent shell within the container, you can try starting the container with the "bash" command. This will launch a bash shell within the container, allowing you to interact with it. You can use the following command:
    ```sh
    docker run -it <image_name> bash
    ```
    Replace <image_name> with the actual name or ID of the connectal-docker image you pulled from Docker Hub.
